// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = DcoCodec,
    default_rust_opaque = RustOpaqueNom,
    default_rust_auto_opaque = RustAutoOpaqueNom,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -1562433680;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__joinstr__initiate_coinjoin_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    config: impl CstDecode<crate::api::types::FfiPoolConfig>,
    peer: impl CstDecode<crate::api::types::FfiPeerConfig>,
    progress: impl CstDecode<
        StreamSink<
            crate::api::types::FfiCoinjoinUpdate,
            flutter_rust_bridge::for_generated::DcoCodec,
        >,
    >,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "initiate_coinjoin",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_config = config.cst_decode();
            let api_peer = peer.cst_decode();
            let api_progress = progress.cst_decode();
            move |context| {
                transform_result_dco::<_, _, crate::api::error::JoinstrError>((move || {
                    let output_ok =
                        crate::api::joinstr::initiate_coinjoin(api_config, api_peer, api_progress)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__joinstr__join_coinjoin_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    pool_raw_json: impl CstDecode<String>,
    peer: impl CstDecode<crate::api::types::FfiPeerConfig>,
    progress: impl CstDecode<
        StreamSink<
            crate::api::types::FfiCoinjoinUpdate,
            flutter_rust_bridge::for_generated::DcoCodec,
        >,
    >,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "join_coinjoin",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_pool_raw_json = pool_raw_json.cst_decode();
            let api_peer = peer.cst_decode();
            let api_progress = progress.cst_decode();
            move |context| {
                transform_result_dco::<_, _, crate::api::error::JoinstrError>((move || {
                    let output_ok = crate::api::joinstr::join_coinjoin(
                        api_pool_raw_json,
                        api_peer,
                        api_progress,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__joinstr__list_coins_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    mnemonic: impl CstDecode<String>,
    electrum_address: impl CstDecode<String>,
    electrum_port: impl CstDecode<u16>,
    range_start: impl CstDecode<u32>,
    range_end: impl CstDecode<u32>,
    network: impl CstDecode<crate::api::types::BitcoinNetwork>,
    proxy: impl CstDecode<Option<String>>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "list_coins",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_mnemonic = mnemonic.cst_decode();
            let api_electrum_address = electrum_address.cst_decode();
            let api_electrum_port = electrum_port.cst_decode();
            let api_range_start = range_start.cst_decode();
            let api_range_end = range_end.cst_decode();
            let api_network = network.cst_decode();
            let api_proxy = proxy.cst_decode();
            move |context| {
                transform_result_dco::<_, _, crate::api::error::JoinstrError>((move || {
                    let output_ok = crate::api::joinstr::list_coins(
                        api_mnemonic,
                        api_electrum_address,
                        api_electrum_port,
                        api_range_start,
                        api_range_end,
                        api_network,
                        api_proxy,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__joinstr__list_pools_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    back: impl CstDecode<u64>,
    timeout: impl CstDecode<u64>,
    relay: impl CstDecode<String>,
    proxy: impl CstDecode<Option<String>>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "list_pools",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_back = back.cst_decode();
            let api_timeout = timeout.cst_decode();
            let api_relay = relay.cst_decode();
            let api_proxy = proxy.cst_decode();
            move |context| {
                transform_result_dco::<_, _, crate::api::error::JoinstrError>((move || {
                    let output_ok = crate::api::joinstr::list_pools(
                        api_back,
                        api_timeout,
                        api_relay,
                        api_proxy,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl CstDecode<crate::api::types::BitcoinNetwork> for i32 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::BitcoinNetwork {
        match self {
            0 => crate::api::types::BitcoinNetwork::Bitcoin,
            1 => crate::api::types::BitcoinNetwork::Testnet,
            2 => crate::api::types::BitcoinNetwork::Signet,
            3 => crate::api::types::BitcoinNetwork::Regtest,
            _ => unreachable!("Invalid variant for BitcoinNetwork: {}", self),
        }
    }
}
impl CstDecode<f64> for f64 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> f64 {
        self
    }
}
impl CstDecode<crate::api::types::FfiCoinjoinStep> for i32 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::FfiCoinjoinStep {
        match self {
            0 => crate::api::types::FfiCoinjoinStep::Connecting,
            1 => crate::api::types::FfiCoinjoinStep::Posting,
            2 => crate::api::types::FfiCoinjoinStep::OutputRegistration,
            3 => crate::api::types::FfiCoinjoinStep::InputRegistration,
            4 => crate::api::types::FfiCoinjoinStep::Broadcast,
            5 => crate::api::types::FfiCoinjoinStep::Mined,
            6 => crate::api::types::FfiCoinjoinStep::Done,
            7 => crate::api::types::FfiCoinjoinStep::Failed,
            8 => crate::api::types::FfiCoinjoinStep::Other,
            _ => unreachable!("Invalid variant for FfiCoinjoinStep: {}", self),
        }
    }
}
impl CstDecode<i32> for i32 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> i32 {
        self
    }
}
impl CstDecode<u16> for u16 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> u16 {
        self
    }
}
impl CstDecode<u32> for u32 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> u32 {
        self
    }
}
impl CstDecode<u64> for u64 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> u64 {
        self
    }
}
impl CstDecode<u8> for u8 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> u8 {
        self
    }
}
impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode
    for StreamSink<
        crate::api::types::FfiCoinjoinUpdate,
        flutter_rust_bridge::for_generated::DcoCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::types::BitcoinNetwork {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::types::BitcoinNetwork::Bitcoin,
            1 => crate::api::types::BitcoinNetwork::Testnet,
            2 => crate::api::types::BitcoinNetwork::Signet,
            3 => crate::api::types::BitcoinNetwork::Regtest,
            _ => unreachable!("Invalid variant for BitcoinNetwork: {}", inner),
        };
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::types::FfiCoin {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_txid = <String>::sse_decode(deserializer);
        let mut var_vout = <u32>::sse_decode(deserializer);
        let mut var_valueSat = <u64>::sse_decode(deserializer);
        let mut var_scriptPubkey = <Vec<u8>>::sse_decode(deserializer);
        let mut var_sequence = <u32>::sse_decode(deserializer);
        let mut var_coinPathDepth = <u32>::sse_decode(deserializer);
        let mut var_coinPathIndex = <Option<u32>>::sse_decode(deserializer);
        return crate::api::types::FfiCoin {
            txid: var_txid,
            vout: var_vout,
            value_sat: var_valueSat,
            script_pubkey: var_scriptPubkey,
            sequence: var_sequence,
            coin_path_depth: var_coinPathDepth,
            coin_path_index: var_coinPathIndex,
        };
    }
}

impl SseDecode for crate::api::types::FfiCoinjoinStep {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::types::FfiCoinjoinStep::Connecting,
            1 => crate::api::types::FfiCoinjoinStep::Posting,
            2 => crate::api::types::FfiCoinjoinStep::OutputRegistration,
            3 => crate::api::types::FfiCoinjoinStep::InputRegistration,
            4 => crate::api::types::FfiCoinjoinStep::Broadcast,
            5 => crate::api::types::FfiCoinjoinStep::Mined,
            6 => crate::api::types::FfiCoinjoinStep::Done,
            7 => crate::api::types::FfiCoinjoinStep::Failed,
            8 => crate::api::types::FfiCoinjoinStep::Other,
            _ => unreachable!("Invalid variant for FfiCoinjoinStep: {}", inner),
        };
    }
}

impl SseDecode for crate::api::types::FfiCoinjoinUpdate {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_step = <crate::api::types::FfiCoinjoinStep>::sse_decode(deserializer);
        let mut var_txid = <Option<String>>::sse_decode(deserializer);
        let mut var_error = <Option<String>>::sse_decode(deserializer);
        return crate::api::types::FfiCoinjoinUpdate {
            step: var_step,
            txid: var_txid,
            error: var_error,
        };
    }
}

impl SseDecode for crate::api::types::FfiPeerConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_mnemonic = <String>::sse_decode(deserializer);
        let mut var_electrumAddress = <String>::sse_decode(deserializer);
        let mut var_electrumPort = <u16>::sse_decode(deserializer);
        let mut var_input = <crate::api::types::FfiCoin>::sse_decode(deserializer);
        let mut var_outputAddress = <String>::sse_decode(deserializer);
        let mut var_relay = <String>::sse_decode(deserializer);
        let mut var_network = <crate::api::types::BitcoinNetwork>::sse_decode(deserializer);
        let mut var_proxy = <Option<String>>::sse_decode(deserializer);
        return crate::api::types::FfiPeerConfig {
            mnemonic: var_mnemonic,
            electrum_address: var_electrumAddress,
            electrum_port: var_electrumPort,
            input: var_input,
            output_address: var_outputAddress,
            relay: var_relay,
            network: var_network,
            proxy: var_proxy,
        };
    }
}

impl SseDecode for crate::api::types::FfiPool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_rawJson = <String>::sse_decode(deserializer);
        let mut var_denominationSat = <u64>::sse_decode(deserializer);
        let mut var_peers = <u32>::sse_decode(deserializer);
        let mut var_expiresAtUnixSec = <u64>::sse_decode(deserializer);
        let mut var_relay = <String>::sse_decode(deserializer);
        let mut var_feeRate = <u32>::sse_decode(deserializer);
        let mut var_publicKey = <String>::sse_decode(deserializer);
        let mut var_version = <Option<String>>::sse_decode(deserializer);
        return crate::api::types::FfiPool {
            id: var_id,
            raw_json: var_rawJson,
            denomination_sat: var_denominationSat,
            peers: var_peers,
            expires_at_unix_sec: var_expiresAtUnixSec,
            relay: var_relay,
            fee_rate: var_feeRate,
            public_key: var_publicKey,
            version: var_version,
        };
    }
}

impl SseDecode for crate::api::types::FfiPoolConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_denominationBtc = <f64>::sse_decode(deserializer);
        let mut var_fee = <u32>::sse_decode(deserializer);
        let mut var_maxDuration = <u64>::sse_decode(deserializer);
        let mut var_peers = <u32>::sse_decode(deserializer);
        let mut var_network = <crate::api::types::BitcoinNetwork>::sse_decode(deserializer);
        return crate::api::types::FfiPoolConfig {
            denomination_btc: var_denominationBtc,
            fee: var_fee,
            max_duration: var_maxDuration,
            peers: var_peers,
            network: var_network,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::error::JoinstrError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_message = <String>::sse_decode(deserializer);
        return crate::api::error::JoinstrError {
            message: var_message,
        };
    }
}

impl SseDecode for Vec<crate::api::types::FfiCoin> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::types::FfiCoin>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::types::FfiPool> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::types::FfiPool>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for u16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u16::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::BitcoinNetwork {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Bitcoin => 0.into_dart(),
            Self::Testnet => 1.into_dart(),
            Self::Signet => 2.into_dart(),
            Self::Regtest => 3.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::BitcoinNetwork
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::BitcoinNetwork>
    for crate::api::types::BitcoinNetwork
{
    fn into_into_dart(self) -> crate::api::types::BitcoinNetwork {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::FfiCoin {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.txid.into_into_dart().into_dart(),
            self.vout.into_into_dart().into_dart(),
            self.value_sat.into_into_dart().into_dart(),
            self.script_pubkey.into_into_dart().into_dart(),
            self.sequence.into_into_dart().into_dart(),
            self.coin_path_depth.into_into_dart().into_dart(),
            self.coin_path_index.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::types::FfiCoin {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::FfiCoin> for crate::api::types::FfiCoin {
    fn into_into_dart(self) -> crate::api::types::FfiCoin {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::FfiCoinjoinStep {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Connecting => 0.into_dart(),
            Self::Posting => 1.into_dart(),
            Self::OutputRegistration => 2.into_dart(),
            Self::InputRegistration => 3.into_dart(),
            Self::Broadcast => 4.into_dart(),
            Self::Mined => 5.into_dart(),
            Self::Done => 6.into_dart(),
            Self::Failed => 7.into_dart(),
            Self::Other => 8.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::FfiCoinjoinStep
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::FfiCoinjoinStep>
    for crate::api::types::FfiCoinjoinStep
{
    fn into_into_dart(self) -> crate::api::types::FfiCoinjoinStep {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::FfiCoinjoinUpdate {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.step.into_into_dart().into_dart(),
            self.txid.into_into_dart().into_dart(),
            self.error.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::FfiCoinjoinUpdate
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::FfiCoinjoinUpdate>
    for crate::api::types::FfiCoinjoinUpdate
{
    fn into_into_dart(self) -> crate::api::types::FfiCoinjoinUpdate {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::FfiPeerConfig {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.mnemonic.into_into_dart().into_dart(),
            self.electrum_address.into_into_dart().into_dart(),
            self.electrum_port.into_into_dart().into_dart(),
            self.input.into_into_dart().into_dart(),
            self.output_address.into_into_dart().into_dart(),
            self.relay.into_into_dart().into_dart(),
            self.network.into_into_dart().into_dart(),
            self.proxy.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::FfiPeerConfig
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::FfiPeerConfig>
    for crate::api::types::FfiPeerConfig
{
    fn into_into_dart(self) -> crate::api::types::FfiPeerConfig {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::FfiPool {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.raw_json.into_into_dart().into_dart(),
            self.denomination_sat.into_into_dart().into_dart(),
            self.peers.into_into_dart().into_dart(),
            self.expires_at_unix_sec.into_into_dart().into_dart(),
            self.relay.into_into_dart().into_dart(),
            self.fee_rate.into_into_dart().into_dart(),
            self.public_key.into_into_dart().into_dart(),
            self.version.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::types::FfiPool {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::FfiPool> for crate::api::types::FfiPool {
    fn into_into_dart(self) -> crate::api::types::FfiPool {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::FfiPoolConfig {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.denomination_btc.into_into_dart().into_dart(),
            self.fee.into_into_dart().into_dart(),
            self.max_duration.into_into_dart().into_dart(),
            self.peers.into_into_dart().into_dart(),
            self.network.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::FfiPoolConfig
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::FfiPoolConfig>
    for crate::api::types::FfiPoolConfig
{
    fn into_into_dart(self) -> crate::api::types::FfiPoolConfig {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::error::JoinstrError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [self.message.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::error::JoinstrError
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::error::JoinstrError>
    for crate::api::error::JoinstrError
{
    fn into_into_dart(self) -> crate::api::error::JoinstrError {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode
    for StreamSink<
        crate::api::types::FfiCoinjoinUpdate,
        flutter_rust_bridge::for_generated::DcoCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::types::BitcoinNetwork {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::types::BitcoinNetwork::Bitcoin => 0,
                crate::api::types::BitcoinNetwork::Testnet => 1,
                crate::api::types::BitcoinNetwork::Signet => 2,
                crate::api::types::BitcoinNetwork::Regtest => 3,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::types::FfiCoin {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.txid, serializer);
        <u32>::sse_encode(self.vout, serializer);
        <u64>::sse_encode(self.value_sat, serializer);
        <Vec<u8>>::sse_encode(self.script_pubkey, serializer);
        <u32>::sse_encode(self.sequence, serializer);
        <u32>::sse_encode(self.coin_path_depth, serializer);
        <Option<u32>>::sse_encode(self.coin_path_index, serializer);
    }
}

impl SseEncode for crate::api::types::FfiCoinjoinStep {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::types::FfiCoinjoinStep::Connecting => 0,
                crate::api::types::FfiCoinjoinStep::Posting => 1,
                crate::api::types::FfiCoinjoinStep::OutputRegistration => 2,
                crate::api::types::FfiCoinjoinStep::InputRegistration => 3,
                crate::api::types::FfiCoinjoinStep::Broadcast => 4,
                crate::api::types::FfiCoinjoinStep::Mined => 5,
                crate::api::types::FfiCoinjoinStep::Done => 6,
                crate::api::types::FfiCoinjoinStep::Failed => 7,
                crate::api::types::FfiCoinjoinStep::Other => 8,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::types::FfiCoinjoinUpdate {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::types::FfiCoinjoinStep>::sse_encode(self.step, serializer);
        <Option<String>>::sse_encode(self.txid, serializer);
        <Option<String>>::sse_encode(self.error, serializer);
    }
}

impl SseEncode for crate::api::types::FfiPeerConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.mnemonic, serializer);
        <String>::sse_encode(self.electrum_address, serializer);
        <u16>::sse_encode(self.electrum_port, serializer);
        <crate::api::types::FfiCoin>::sse_encode(self.input, serializer);
        <String>::sse_encode(self.output_address, serializer);
        <String>::sse_encode(self.relay, serializer);
        <crate::api::types::BitcoinNetwork>::sse_encode(self.network, serializer);
        <Option<String>>::sse_encode(self.proxy, serializer);
    }
}

impl SseEncode for crate::api::types::FfiPool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.raw_json, serializer);
        <u64>::sse_encode(self.denomination_sat, serializer);
        <u32>::sse_encode(self.peers, serializer);
        <u64>::sse_encode(self.expires_at_unix_sec, serializer);
        <String>::sse_encode(self.relay, serializer);
        <u32>::sse_encode(self.fee_rate, serializer);
        <String>::sse_encode(self.public_key, serializer);
        <Option<String>>::sse_encode(self.version, serializer);
    }
}

impl SseEncode for crate::api::types::FfiPoolConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f64>::sse_encode(self.denomination_btc, serializer);
        <u32>::sse_encode(self.fee, serializer);
        <u64>::sse_encode(self.max_duration, serializer);
        <u32>::sse_encode(self.peers, serializer);
        <crate::api::types::BitcoinNetwork>::sse_encode(self.network, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::error::JoinstrError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.message, serializer);
    }
}

impl SseEncode for Vec<crate::api::types::FfiCoin> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::types::FfiCoin>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::types::FfiPool> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::types::FfiPool>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for u16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u16::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();

    // Section: dart2rust

    impl CstDecode<flutter_rust_bridge::for_generated::anyhow::Error>
        for *mut wire_cst_list_prim_u_8_strict
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> flutter_rust_bridge::for_generated::anyhow::Error {
            unimplemented!()
        }
    }
    impl
        CstDecode<
            StreamSink<
                crate::api::types::FfiCoinjoinUpdate,
                flutter_rust_bridge::for_generated::DcoCodec,
            >,
        > for *mut wire_cst_list_prim_u_8_strict
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(
            self,
        ) -> StreamSink<
            crate::api::types::FfiCoinjoinUpdate,
            flutter_rust_bridge::for_generated::DcoCodec,
        > {
            let raw: String = self.cst_decode();
            StreamSink::deserialize(raw)
        }
    }
    impl CstDecode<String> for *mut wire_cst_list_prim_u_8_strict {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> String {
            let vec: Vec<u8> = self.cst_decode();
            String::from_utf8(vec).unwrap()
        }
    }
    impl CstDecode<crate::api::types::FfiPeerConfig> for *mut wire_cst_ffi_peer_config {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::types::FfiPeerConfig {
            let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
            CstDecode::<crate::api::types::FfiPeerConfig>::cst_decode(*wrap).into()
        }
    }
    impl CstDecode<crate::api::types::FfiPoolConfig> for *mut wire_cst_ffi_pool_config {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::types::FfiPoolConfig {
            let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
            CstDecode::<crate::api::types::FfiPoolConfig>::cst_decode(*wrap).into()
        }
    }
    impl CstDecode<u32> for *mut u32 {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> u32 {
            unsafe { *flutter_rust_bridge::for_generated::box_from_leak_ptr(self) }
        }
    }
    impl CstDecode<crate::api::types::FfiCoin> for wire_cst_ffi_coin {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::types::FfiCoin {
            crate::api::types::FfiCoin {
                txid: self.txid.cst_decode(),
                vout: self.vout.cst_decode(),
                value_sat: self.value_sat.cst_decode(),
                script_pubkey: self.script_pubkey.cst_decode(),
                sequence: self.sequence.cst_decode(),
                coin_path_depth: self.coin_path_depth.cst_decode(),
                coin_path_index: self.coin_path_index.cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::types::FfiCoinjoinUpdate> for wire_cst_ffi_coinjoin_update {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::types::FfiCoinjoinUpdate {
            crate::api::types::FfiCoinjoinUpdate {
                step: self.step.cst_decode(),
                txid: self.txid.cst_decode(),
                error: self.error.cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::types::FfiPeerConfig> for wire_cst_ffi_peer_config {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::types::FfiPeerConfig {
            crate::api::types::FfiPeerConfig {
                mnemonic: self.mnemonic.cst_decode(),
                electrum_address: self.electrum_address.cst_decode(),
                electrum_port: self.electrum_port.cst_decode(),
                input: self.input.cst_decode(),
                output_address: self.output_address.cst_decode(),
                relay: self.relay.cst_decode(),
                network: self.network.cst_decode(),
                proxy: self.proxy.cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::types::FfiPool> for wire_cst_ffi_pool {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::types::FfiPool {
            crate::api::types::FfiPool {
                id: self.id.cst_decode(),
                raw_json: self.raw_json.cst_decode(),
                denomination_sat: self.denomination_sat.cst_decode(),
                peers: self.peers.cst_decode(),
                expires_at_unix_sec: self.expires_at_unix_sec.cst_decode(),
                relay: self.relay.cst_decode(),
                fee_rate: self.fee_rate.cst_decode(),
                public_key: self.public_key.cst_decode(),
                version: self.version.cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::types::FfiPoolConfig> for wire_cst_ffi_pool_config {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::types::FfiPoolConfig {
            crate::api::types::FfiPoolConfig {
                denomination_btc: self.denomination_btc.cst_decode(),
                fee: self.fee.cst_decode(),
                max_duration: self.max_duration.cst_decode(),
                peers: self.peers.cst_decode(),
                network: self.network.cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::error::JoinstrError> for wire_cst_joinstr_error {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::error::JoinstrError {
            crate::api::error::JoinstrError {
                message: self.message.cst_decode(),
            }
        }
    }
    impl CstDecode<Vec<crate::api::types::FfiCoin>> for *mut wire_cst_list_ffi_coin {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<crate::api::types::FfiCoin> {
            let vec = unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            };
            vec.into_iter().map(CstDecode::cst_decode).collect()
        }
    }
    impl CstDecode<Vec<crate::api::types::FfiPool>> for *mut wire_cst_list_ffi_pool {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<crate::api::types::FfiPool> {
            let vec = unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            };
            vec.into_iter().map(CstDecode::cst_decode).collect()
        }
    }
    impl CstDecode<Vec<u8>> for *mut wire_cst_list_prim_u_8_strict {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<u8> {
            unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            }
        }
    }
    impl NewWithNullPtr for wire_cst_ffi_coin {
        fn new_with_null_ptr() -> Self {
            Self {
                txid: core::ptr::null_mut(),
                vout: Default::default(),
                value_sat: Default::default(),
                script_pubkey: core::ptr::null_mut(),
                sequence: Default::default(),
                coin_path_depth: Default::default(),
                coin_path_index: core::ptr::null_mut(),
            }
        }
    }
    impl Default for wire_cst_ffi_coin {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_ffi_coinjoin_update {
        fn new_with_null_ptr() -> Self {
            Self {
                step: Default::default(),
                txid: core::ptr::null_mut(),
                error: core::ptr::null_mut(),
            }
        }
    }
    impl Default for wire_cst_ffi_coinjoin_update {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_ffi_peer_config {
        fn new_with_null_ptr() -> Self {
            Self {
                mnemonic: core::ptr::null_mut(),
                electrum_address: core::ptr::null_mut(),
                electrum_port: Default::default(),
                input: Default::default(),
                output_address: core::ptr::null_mut(),
                relay: core::ptr::null_mut(),
                network: Default::default(),
                proxy: core::ptr::null_mut(),
            }
        }
    }
    impl Default for wire_cst_ffi_peer_config {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_ffi_pool {
        fn new_with_null_ptr() -> Self {
            Self {
                id: core::ptr::null_mut(),
                raw_json: core::ptr::null_mut(),
                denomination_sat: Default::default(),
                peers: Default::default(),
                expires_at_unix_sec: Default::default(),
                relay: core::ptr::null_mut(),
                fee_rate: Default::default(),
                public_key: core::ptr::null_mut(),
                version: core::ptr::null_mut(),
            }
        }
    }
    impl Default for wire_cst_ffi_pool {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_ffi_pool_config {
        fn new_with_null_ptr() -> Self {
            Self {
                denomination_btc: Default::default(),
                fee: Default::default(),
                max_duration: Default::default(),
                peers: Default::default(),
                network: Default::default(),
            }
        }
    }
    impl Default for wire_cst_ffi_pool_config {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_joinstr_error {
        fn new_with_null_ptr() -> Self {
            Self {
                message: core::ptr::null_mut(),
            }
        }
    }
    impl Default for wire_cst_joinstr_error {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_joinstr_flutter_wire__crate__api__joinstr__initiate_coinjoin(
        port_: i64,
        config: *mut wire_cst_ffi_pool_config,
        peer: *mut wire_cst_ffi_peer_config,
        progress: *mut wire_cst_list_prim_u_8_strict,
    ) {
        wire__crate__api__joinstr__initiate_coinjoin_impl(port_, config, peer, progress)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_joinstr_flutter_wire__crate__api__joinstr__join_coinjoin(
        port_: i64,
        pool_raw_json: *mut wire_cst_list_prim_u_8_strict,
        peer: *mut wire_cst_ffi_peer_config,
        progress: *mut wire_cst_list_prim_u_8_strict,
    ) {
        wire__crate__api__joinstr__join_coinjoin_impl(port_, pool_raw_json, peer, progress)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_joinstr_flutter_wire__crate__api__joinstr__list_coins(
        port_: i64,
        mnemonic: *mut wire_cst_list_prim_u_8_strict,
        electrum_address: *mut wire_cst_list_prim_u_8_strict,
        electrum_port: u16,
        range_start: u32,
        range_end: u32,
        network: i32,
        proxy: *mut wire_cst_list_prim_u_8_strict,
    ) {
        wire__crate__api__joinstr__list_coins_impl(
            port_,
            mnemonic,
            electrum_address,
            electrum_port,
            range_start,
            range_end,
            network,
            proxy,
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_joinstr_flutter_wire__crate__api__joinstr__list_pools(
        port_: i64,
        back: u64,
        timeout: u64,
        relay: *mut wire_cst_list_prim_u_8_strict,
        proxy: *mut wire_cst_list_prim_u_8_strict,
    ) {
        wire__crate__api__joinstr__list_pools_impl(port_, back, timeout, relay, proxy)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_joinstr_flutter_cst_new_box_autoadd_ffi_peer_config(
    ) -> *mut wire_cst_ffi_peer_config {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(
            wire_cst_ffi_peer_config::new_with_null_ptr(),
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_joinstr_flutter_cst_new_box_autoadd_ffi_pool_config(
    ) -> *mut wire_cst_ffi_pool_config {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(
            wire_cst_ffi_pool_config::new_with_null_ptr(),
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_joinstr_flutter_cst_new_box_autoadd_u_32(value: u32) -> *mut u32 {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(value)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_joinstr_flutter_cst_new_list_ffi_coin(
        len: i32,
    ) -> *mut wire_cst_list_ffi_coin {
        let wrap = wire_cst_list_ffi_coin {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(
                <wire_cst_ffi_coin>::new_with_null_ptr(),
                len,
            ),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(wrap)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_joinstr_flutter_cst_new_list_ffi_pool(
        len: i32,
    ) -> *mut wire_cst_list_ffi_pool {
        let wrap = wire_cst_list_ffi_pool {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(
                <wire_cst_ffi_pool>::new_with_null_ptr(),
                len,
            ),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(wrap)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_joinstr_flutter_cst_new_list_prim_u_8_strict(
        len: i32,
    ) -> *mut wire_cst_list_prim_u_8_strict {
        let ans = wire_cst_list_prim_u_8_strict {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(Default::default(), len),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(ans)
    }

    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_ffi_coin {
        txid: *mut wire_cst_list_prim_u_8_strict,
        vout: u32,
        value_sat: u64,
        script_pubkey: *mut wire_cst_list_prim_u_8_strict,
        sequence: u32,
        coin_path_depth: u32,
        coin_path_index: *mut u32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_ffi_coinjoin_update {
        step: i32,
        txid: *mut wire_cst_list_prim_u_8_strict,
        error: *mut wire_cst_list_prim_u_8_strict,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_ffi_peer_config {
        mnemonic: *mut wire_cst_list_prim_u_8_strict,
        electrum_address: *mut wire_cst_list_prim_u_8_strict,
        electrum_port: u16,
        input: wire_cst_ffi_coin,
        output_address: *mut wire_cst_list_prim_u_8_strict,
        relay: *mut wire_cst_list_prim_u_8_strict,
        network: i32,
        proxy: *mut wire_cst_list_prim_u_8_strict,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_ffi_pool {
        id: *mut wire_cst_list_prim_u_8_strict,
        raw_json: *mut wire_cst_list_prim_u_8_strict,
        denomination_sat: u64,
        peers: u32,
        expires_at_unix_sec: u64,
        relay: *mut wire_cst_list_prim_u_8_strict,
        fee_rate: u32,
        public_key: *mut wire_cst_list_prim_u_8_strict,
        version: *mut wire_cst_list_prim_u_8_strict,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_ffi_pool_config {
        denomination_btc: f64,
        fee: u32,
        max_duration: u64,
        peers: u32,
        network: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_joinstr_error {
        message: *mut wire_cst_list_prim_u_8_strict,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_ffi_coin {
        ptr: *mut wire_cst_ffi_coin,
        len: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_ffi_pool {
        ptr: *mut wire_cst_ffi_pool,
        len: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_prim_u_8_strict {
        ptr: *mut u8,
        len: i32,
    }
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;
