[package]
name = "simple_nostr_client"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { workspace = true }
socks5 = { workspace = true }
nostr = { workspace = true, features = ["nip04"] }
tungstenite = { workspace = true }
rustls = { workspace = true }
webpki-roots = { workspace = true }
backoff = { workspace = true }


[dev-dependencies]
nostrd = { workspace = true }
env_logger = "0.11.6"
joinstr = { workspace = true }
